### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by vv-monsalve** [xotypeco/big_shoulders#11]
When comparing the current static fonts with the one on the API, the vertical metrics are not the same. This sort of change must be avoided when updating a font to ensure fonts do not break existing documents or websites. ([https://github.com/googlefonts/gf-docs/tree/master/Spec#scalable-font-production](https://github.com/googlefonts/gf-docs/tree/master/Spec#scalable-font-production)).

Data comparison between the .ttf on the API _(string a)_, and the current static .ttf on the repository _(string b)_:

![Screen Shot 2020-05-14 at 12 38 39](https://user-images.githubusercontent.com/48698976/81966995-e4608d80-95df-11ea-8376-59b0a624aef5.png)

Changes to Diacritics on the font are demanding higher values, but, this could be avoided by adjusting the size, weight, slope, or position of them in complex compound glyphs like the Aringacute or the Vietnamese.

![Aringacute](https://user-images.githubusercontent.com/48698976/81990885-aa09e700-9605-11ea-8db5-3d36c545cd66.gif)

**Comment by xotypeco** [comment]
change in vertical metric comes from a couple of actual design changes:

1)  a change change in the overall weight and color of diacritics to improve how it looks and reads. 

2) I deleted an overly-fussy set of diacritics for .case and replaced it with a standard set for both uppers and lowers. 

note in frame one, ring is lighter and crashes into the character. I changed that to get what you see in frame two. same for the acute, it is steeper and heavier. both changes made to give diacritics a more consistent color and behavior across families—I didn't discover that the crashing ring was a terrible idea until dealing with Inline.

**Comment by davelab6** [comment]
This kind of height increase in an update is more typical when Vietnamese support is added. I believe the latest v metrics recommendation from @m4rc1e means that this doesn't cause an issue on the web, only on Android (which uses the bbox rather than v metrics, fml)

**Comment by vv-monsalve** [comment]
Well, AFAIK @m4rc1e was really against the VM values changing when updating fonts, to avoid breaking anything down on documents or websites that are already using it.
[If the family is being updated, the line height must visually match the previous release.](https://github.com/googlefonts/gf-docs/tree/master/VerticalMetrics#6-if-the-family-is-being-updated-the-line-height-must-visually-match-the-previous-release)

**Comment by m4rc1e** [comment]
@vv-monsalve do the new vertical metrics alter the visual appearance? 

I don't mind if the winAscent and winDescent have been changed if fsSelection bit 7 has been enabled.

**Comment by vv-monsalve** [comment]
@m4rc1e yep, you are right. Bit 7 is enabled and no visual appearance was altered. I couldn't test it yesterday, but doing now on [cyreal.org](http://www.cyreal.org/) it looks just fine.
Closing this here.

**Comment by m4rc1e** [comment]
@vv-monsalve Did you also check Win Chrome?

**Comment by vv-monsalve** [comment]
These are the **Browser diffs and previews Result**
Comparative gifs after running a [Dispatcher sandox](https://fontbakery.graphicore.de/dispatcher/process/302dc42e-142a-4cdd-a415-8f63803852a7) cheks
They look ok to me, wdyt?

**Big Shoulder Text Black**
**Safari Sierra 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/82065828-38c54500-9694-11ea-89aa-03dcaa54ba82.gif)
**Windows 10 Chrome 69**
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/82065845-3d89f900-9694-11ea-88fb-e2b9d78981d2.gif)
**Windows 10 Firefox 62**
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/82065849-3e228f80-9694-11ea-8486-1a82abe49857.gif)

**Comment by vv-monsalve** [comment]
Although, this sample doesn't display critical cases such as Vietnamese characters. A further check might be needed in that context.

**Comment by xotypeco** [comment]
diffs look great. I broadened some kerning pairs based on what I saw going wrong in the city's COVID-19 video captions, this seems to reflect that OK.

**Comment by vv-monsalve** [comment]
Vertical Metrics regarding Vietnamese can be tested with a basic HTML with Vietnamese texts, to ensure there would be no clipping, and to check it on Windows browsers. See this as a [reference](https://github.com/vv-monsalve/space-grotesk/issues/13).
