### ISSUE TITLE
Diffenator and Diff Browsers new main results

### ISSUE THREAD

**Issue by vv-monsalve** [xotypeco/big_shoulders#14]
### Big Shoulders Text Regular

**Browser Diff / Chrome 69**

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/83475189-73302f80-a453-11ea-939b-091bcadc338e.gif)

Comparative images 

![glyphs_modified](https://user-images.githubusercontent.com/48698976/83475370-d621c680-a453-11ea-86b1-d281dd681fc0.gif)

![kerns_missing](https://user-images.githubusercontent.com/48698976/83475408-ea65c380-a453-11ea-9c5f-3b86582274fc.gif)

![marks_modified](https://user-images.githubusercontent.com/48698976/83475447-fd789380-a453-11ea-9620-312149852b3f.gif)

![marks_missing](https://user-images.githubusercontent.com/48698976/83475425-f3ef2b80-a453-11ea-9973-b11c688b7145.gif)

**Comment by vv-monsalve** [comment]
### Big Shoulders Text Bold

**Browser Diff / Chrome 69**

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/83475667-68c26580-a454-11ea-9df3-f7bafe4311da.gif)

Comparative images

![glyphs_modified](https://user-images.githubusercontent.com/48698976/83475580-3e70a800-a454-11ea-9855-4cea6e58199c.gif)

![kerns_missing](https://user-images.githubusercontent.com/48698976/83475597-47fa1000-a454-11ea-9ce1-d462cf7059b1.gif)

![marks_modified](https://user-images.githubusercontent.com/48698976/83475622-52b4a500-a454-11ea-934f-08010c369d0c.gif)

![marks_missing](https://user-images.githubusercontent.com/48698976/83475639-5a744980-a454-11ea-9519-1747c57935bd.gif)

**Comment by xotypeco** [comment]
the changed marks and kerning are expected; the last set of missing marks are a mistake. it looks like I forgot to fix some anchors. will fix. thanks, Viviana.

**Comment by vv-monsalve** [comment]
### Big Shoulders Display Regular

**Browser Diff / Chrome 69**

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/83477029-c7d5a980-a457-11ea-8687-0a87a2fdc414.gif)

**Comparative images**

![glyphs_modified](https://user-images.githubusercontent.com/48698976/83476610-c35cc100-a456-11ea-9167-098d452e14c3.gif)

![kerns_missing](https://user-images.githubusercontent.com/48698976/83476657-dff8f900-a456-11ea-9055-88fe0e5ee48d.gif)

![kerns_modified](https://user-images.githubusercontent.com/48698976/83476667-e7b89d80-a456-11ea-8a5f-6799c1f13741.gif)

![marks_modified](https://user-images.githubusercontent.com/48698976/83476690-f901aa00-a456-11ea-8b4a-2894feb459db.gif)

![marks_missing](https://user-images.githubusercontent.com/48698976/83476702-01f27b80-a457-11ea-93b8-b411ffb4310a.gif)

**Comment by vv-monsalve** [comment]
> the changed marks and kerning are expected; the last set of missing marks are a mistake. it looks like I forgot to fix some anchors. will fix. thanks, Viviana.

Yes, don't worry. It's possible some of them are expected, the images are helpful to confirm everything.

**Comment by xotypeco** [comment]
question: does this mean that the kerning pairs are being shown as *completely missing*? I'm going through them and in most cases (LT in particular) it's values I’ve opened, but they're still tightened.

**Comment by vv-monsalve** [comment]
Sometimes it is due to exceptions on some Kerning class. So the leader letter has the right value, but some related that should have the same value is appearing as an exception and has a different one or none at all. 

Did you check the source or directly the interpolated instance? Sometimes the source doesn't have any problem, but the resulting font yes. It could lead to some hints on the matter.

In any case, for the variable, it would be needed that all the masters have the same amount of kerning pairs, so if it is a kerning pair in one master but none in the other, that last should be at least '0'.

**Comment by xotypeco** [comment]
`Did you check the source or directly the interpolated instance?`

I checked source, but I stopped before I got through everything, to ask you. is it possible for you (or me, for that matter) to generate a text file with all those kerning pairs showing exceptions?

**Comment by xotypeco** [comment]
a little more information I just found, which might help: I was experimenting with a sample string from the first line of kerns reported as missing ( LT ĿT ĽT ḶT ŁT ḺT Tṥ Tṩ Tṡ T… T· T: ) and those kerns do actually exist & work as expected in the generated files from your repo fork (I tested in Adobe Illustrator.) hopefully that points to how this result is occurring.

**Comment by vv-monsalve** [comment]
> I checked source, but I stopped before I got through everything, to ask you. is it possible for you (or me, for that matter) to generate a text file with all those kerning pairs showing exceptions?

Diffenator automatically generates those. Nevertheless, you can find [here](https://github.com/googlefonts/fontbakery/issues/2739) a rich source of strings for kerning

**Comment by xotypeco** [comment]
ok. I’m not really sure how to address this. those diffenator results appear to be literally reporting incorrect information, [per my testing here. ](https://github.com/xotypeco/big_shoulders/issues/14#issuecomment-640081910)

**Comment by vv-monsalve** [comment]
> a little more information I just found, which might help: I was experimenting with a sample string from the first line of kerns reported as missing ( LT ĿT ĽT ḶT ŁT ḺT Tṥ Tṩ Tṡ T… T· T: ) and those kerns do actually exist & work as expected in the generated fonts from your repo fork (I tested in Adobe Illustrator.) hopefully that points to how this result is occurring.

Ok, that might help. However, maybe a double-check on how the fonts behave on browsers could be sensible. You could test that in the same Html to test the Vietnamese. Also, [Cyreal Font Testing Page](http://www.cyreal.org/Font-Testing-Page/index.php) displays some kerning examples.

**Comment by xotypeco** [comment]
everything works as it should at the Cyreal page (see screenshots with some carets to show where the kern happens).

[here's the Vietnamese page](https://xotype.co/bigshoulders/). it's fine. no clipping that I could find.
![Screen Shot 2020-06-06 at 1 31 59 PM](https://user-images.githubusercontent.com/52611676/83953466-4dfe4100-a806-11ea-88aa-ebd92cc59052.png)
![Screen Shot 2020-06-06 at 1 32 44 PM](https://user-images.githubusercontent.com/52611676/83953467-4e96d780-a806-11ea-990d-6a6c89b86ae9.png)
![Screen Shot 2020-06-06 at 1 32 52 PM](https://user-images.githubusercontent.com/52611676/83953468-4f2f6e00-a806-11ea-81d7-646bde036b37.png)
![Screen Shot 2020-06-06 at 1 33 02 PM](https://user-images.githubusercontent.com/52611676/83953469-4f2f6e00-a806-11ea-98f5-75747741c0dd.png)

**Comment by vv-monsalve** [comment]
Checking it in Cyreal the paragraphs seem to be ok with no-reflow happening on the text as it in Diffentor previews.

![BigShoulders-Cyreal](https://user-images.githubusercontent.com/48698976/83960078-29c45380-a84a-11ea-8ddb-adf2b94f81f9.gif)

----

The Vietnamese preview on Windows browsers seems to be clipping free. Now, you might want to check letters with horn (like uhorn and horn) are touching the adjacent glyphs, which may lead to legibility issues. Also, to increase space between these diacritics, it looks like they are overlapping with each other or the base letter (e.g., ắ).

<img width="1440" alt="BigShoulders-Reg_Win_Chrome_83" src="https://user-images.githubusercontent.com/48698976/83960468-c983e080-a84e-11ea-81bc-332141261c91.png">
<img width="1440" alt="BigShoulders-Reg_Win_Edge_83" src="https://user-images.githubusercontent.com/48698976/83960469-cee12b00-a84e-11ea-8559-c4e770319744.png">
<img width="1440" alt="BigShoulders-Reg_Win_Firefox_77" src="https://user-images.githubusercontent.com/48698976/83960471-d1438500-a84e-11ea-84c4-49e2fd4190ed.png">
<img width="1440" alt="BigShoulders-Reg_Win_Opera_68" src="https://user-images.githubusercontent.com/48698976/83960473-d30d4880-a84e-11ea-8b46-7f0e902e3f6d.png">

**Comment by vv-monsalve** [comment]
Beyond those Vietnamese improvements, I think it would be ok for the update, however, I would like to know @m4rc1e  thoughts.

**Comment by xotypeco** [comment]
I'm working on the Vietnamese now. (I made a fork of your fork to catch the changes you made, just as an FYI.) I'm changing the hook by moving it up & making it ia little bigger in lighter weights; the size is a mistake. it looks like a little spot at small sizes.

**Comment by xotypeco** [comment]
ok, all this is fixed up and all changes merged to master. Vietnamese also updated at [proofs here.](https://xotype.co/bigshoulders/)

**Comment by vv-monsalve** [comment]
> yes, all as expected. thanks!

Great, so can we go ahead with this variant? Is the source file on your master the latest, ready to resume QA?

**Comment by xotypeco** [comment]
I need to double check all those kerns one more time to make sure everything interpolates. i had forgotten that from your first batch of findings. will let know know when done; I think I can get them solidified tomorrow.

**Comment by vv-monsalve** [comment]
Ok, let me know

**Comment by xotypeco** [comment]
ok, Big Shoulders source pushed to master with all those edits. one edit further: I set the origin to text light rather than to add another master.

**Comment by vv-monsalve** [comment]
> ok, Big Shoulders source pushed to master with all those edits. one edit further: I set the origin to text light rather than to add another master.

Ok, great! I'll pull it now

> Big Shoulders Stencil is also pushed, but that one's not final yet. it needs kerning to be equal in all masters. I'm doing that tomorrow & will let you know when it's ready.

Good. what would it be for Big Shoulders Inline?

**Comment by xotypeco** [comment]
`Good. what would it be for Big Shoulders Inline?`

probably Tuesday at latest.

for that one, I need to fix the missing diacritics you'd found Big Shoulders, doublecheck Vietnamese hook mark (I think that one's fine), Uhorn and Ohorn sidebearings, and import metrics from Big Shoulders.

**Comment by xotypeco** [comment]
Stencil updated for you. on to Inline next.

**Comment by xotypeco** [comment]
surprise, Inline is also pushed! it turned out to be substantially easier than Big Shoulders or Stencil to update metrics in the Vietnamese because the base characters with horns weren't made of base-and-accent pairs. the horn is drawn connected to the base in that character.

I think you have everything you need; lmk if you run across anything amiss and I’ll correct it asap. Vietnamese proof for Inline coming shortly.

**Comment by xotypeco** [comment]
ok, got kerning fixed. the first import gave me some *really* weird results.

[Vietnamese testing is here.](https://xotype.co/bigshoulders_inline/)

**Comment by vv-monsalve** [comment]
Latest Browsers previews

OS X Sierra Safari 11
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/85799619-23b4ea80-b705-11ea-8b1b-c11d619444c2.gif)

Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/85799630-26afdb00-b705-11ea-9ae3-d6d15b967804.gif)

Windows 10 Firefox 62
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/85799633-27487180-b705-11ea-909b-7230e429284b.gif)
