### ISSUE TITLE
build.sh:22 replace `woff2_compress` with `fontTools ttLib.woff2 compress`

### ISSUE THREAD

**Issue by davelab6** [xotypeco/big_shoulders#21]
In a private email @xotypeco said of #20 

> branch merged. the operation build.sh failed & complained a bit about it though
>
> if I’m reading this correctly, this is the only error:
>
> ./build.sh: line 22: woff2_compress: command not found

That tool is deprecated, it can be replaced with these 2 commands

    pip3 install fonttools brotli;
    python3 -m fontTools ttLib.woff2 compress font.ttf;

cc @chrissimpkins @xotypeco @vv-monsalve

**Comment by vv-monsalve** [comment]
Thanks, @davelab6.  I implemented it and it worked. Strangely, the woff2_compress command was working locally.

After that, a [new error](https://github.com/vv-monsalve/big_shoulders/runs/933540010?check_suite_focus=true#step:6:4672) was reported: `No module named 'fontbakery'` despite I didn't change anything else on the requirements file.

When working locally after `pip install -r requirements.txt`, I usually have to add `pip install gftools[qa]` to have Fontbakey installed (it doesn't work when included in the requirements file)

To solve the reported error in the action, this time I added `Fontbakery` directly into the requirements file. It is working well in the upstream GitHub [actions](https://github.com/vv-monsalve/big_shoulders/actions/runs/190758377). But locally, the FB reports on statics .ttf are reporting an error.

<details>
<summary>💔 <b>ERROR:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* 💔 **ERROR** Failed with TypeError: __new__() missing 6 required positional arguments: 'xx', 'xy', 'yx', 'yy', 'dx', and 'dy'

</details>

@felipesanches should I file an Issue for this? or it is just something that I'm doing wrong in the process?

**Comment by vv-monsalve** [comment]
Forget about it, I repeat the same process with the same command after merging to the master branch and it is working…

**Comment by davelab6** [comment]
Fixed by #22

**Comment by chrissimpkins** [comment]
This might be a situation where you need a virtual environment if you are not using one Viviana.  For the remote GH Actions build fontbakery does not need to be specified anywhere else.  The configuration file takes care of the installation.
