### ISSUE TITLE
Nested Components

### ISSUE THREAD

**Issue by vv-monsalve** [xotypeco/big_shoulders#28]
After performing new v.0.7.34 FB test on the current fonts there is a new Fail reported regarding Nested Components.

This is related to the [Outline Quality Checklist](https://github.com/xotypeco/big_shoulders/issues/27) that we have implemented to avoid some common issues reported.

<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components.</summary>

* [com.google.fonts/check/glyf_nested_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/glyf_nested_components)
<pre>--- Rationale ---

There have been bugs rendering variable fonts with nested components.
Additionally, some static fonts with nested components have been reported to
have rendering and printing issues.

For more info, see:
* https://github.com/googlefonts/fontbakery/issues/2961
* https://github.com/arrowtype/recursive/issues/412

</pre>

* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* uni1EAE
	* uni1EB0
	* uni1EB2
	* uni1EB4
	* uni1EA4
	* uni1EA6
	* uni1EA8
	* uni1EAA
	* uni0202
	* uni1E0E and 142 more. [code: found-nested-components]

</details>

**Comment by xotypeco** [comment]
can you post this full list from your FB results? I’ll start cleanup.

(this is only on Big Shoulders so far, no checks yet run on stencil or inline, correct?)

**Comment by vv-monsalve** [comment]
Sure. I think I'll better upload a folder with the latest reports as there would be at three for the variable fonts and two for the statics per each family.

Also, there is a newly implemented flag (option) in Fontmake to flatten components. I would like to give it a try in the Big Shoulders build, so we could see how far it would help in the process :)

**Comment by xotypeco** [comment]
hey VV, I'm finally getting out from under the Vietnamese fixes for this & getting into this. where'd you post those new FB reports? couldn't find them. (I think all I *really* need is the list of all the nested components; there were about 150, if that's more readily at hand.)

**Comment by vv-monsalve** [comment]
Hi Patric, 

>  where'd you post those new FB reports?

They were included in the [latest PR](https://github.com/xotypeco/big_shoulders/pull/29) at each directory, statics and VF's. E.g., [fonts/ttf/Big-Shoulders-Inline/qaBigShoulders-new-InText-03.md](https://github.com/xotypeco/big_shoulders/blob/master/fonts/ttf/Big-Shoulders-Inline/qaBigShoulders-new-InText-03.md)

> (I think all I really need is the list of all the nested components; there were about 150, if that's more readily at hand.)

Let's give a try to the new `-f` flag for fontmake first

**Comment by xotypeco** [comment]
ah, there we go, thank you. 

> Let's give a try to the new -f flag for fontmake first

use the new -f flag before decomposing anything? yes? (making sure I understood.)

**Comment by vv-monsalve** [comment]
> use the new -f flag before decomposing anything? yes? (making sure I understood.)

Yes, to try it first before decomposing anything. We'll see after using it how it worked if some manual decomposing would be needed.

Let me know once you have pushed new sources so that I can make the change in the build script without github conflicts.

**Comment by xotypeco** [comment]
new masters for all three styles pushed.

there are a few characters decomposed to be safe: I, j, exclamation, question, colon, semicolon. the referenced period kept falling out of alignment in previous versions, and I'd rather be safe than sorry in those characters due to frequency.

other diacritics with nested components are still as they were so you can test -f.

**Comment by xotypeco** [comment]
hey Viviana, I found some other things that need to change in my Vietnamese: acutes and graves need to move in a few cases. commenting before changing anything so I don't mess up your work! let me know if ok to proceed, or if I should wait.

**Comment by vv-monsalve** [comment]
Hi Patric, thank you for confirming this with me before adding the changes. I'll not be able to resume the process for Big Shoulders until the end of this week, so, please proceed with the changes if they won't take longer than that and keep me posted in any case ;)

**Comment by xotypeco** [comment]
I’ll definitely be done before end of week. I’ll post when I push new sources. thanks!

**Comment by xotypeco** [comment]
just pushed new masters. turned out it was only two characters per master that needed adjustment.
