### ISSUE TITLE
Vietnamese previews

### ISSUE THREAD

**Issue by vv-monsalve** [xotypeco/big_shoulders#30]
After pulling the latest files in the repo at commit 3ac9542e9f81b8bcc9fc96c3868c4715c8683f40, produced new fonts and run some test, these are the comparative images for the Vietnamese in the Family

### Big Shoulders Display 

**Thin-Light-Regular-Medium**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/107554275-ba0a2380-6ba3-11eb-8292-0dbcff218bad.gif)

**SemiBold-Bold-ExtraBold-Black**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/107554344-d1491100-6ba3-11eb-996e-5992f662fd02.gif)

**Comment by davelab6** [comment]
Some things have broken. In the first image, the before is good:

<img width="21" alt="Screen Shot 2021-02-10 at 13 47 12" src="https://user-images.githubusercontent.com/261579/107556518-82e94180-6ba6-11eb-9cf8-137fa179e4a4.png">

The after is bad:

<img width="24" alt="Screen Shot 2021-02-10 at 13 47 09" src="https://user-images.githubusercontent.com/261579/107556516-8250ab00-6ba6-11eb-9985-341234406923.png">

You can always ask @crystaltype to review Vietnamese stuff, although she is on vacation for [Tet](https://www.officeholidays.com/holidays/vietnam/tet-nguyen-dan) this week

**Comment by xotypeco** [comment]
strictly speaking, both are correct. second one is the preference in most cases. 

I changed it because there is SO MUCH waste of vertical space with the acute & grave directly on top. also, hook was alredy off to the right, so it made no sense for acute & grave to be on top.

anyway, in other typefaces, for comparison:

here’s Recursive:




here’s Myriad:



I have been working with local native viet speakers on this

**Comment by xotypeco** [comment]
change in width is expected, due to change in horned u and o forms. newer one is narrower to allow better typesetting.

old:



new:

**Comment by vv-monsalve** [comment]
> anyway, in other typefaces, for comparison:

Just in case, the images aren't displayed.

> strictly speaking, both are correct. second one is the preference in most cases.

The position is valid and sometimes even preferred. However, the legibility of stacked diacritics is crucial, thus you would like to review:

- the proximity between marks (both horizontal and vertical, e.g. horn + tilde; tilde + circumflex) 
- the distance to the glyph (e.g. circumflex or tilde)
- the size of the diacritic (e.g. tilde could be subtle narrow and some of the above would improve)

![Screen Shot 2021-02-10 at 15 47 11](https://user-images.githubusercontent.com/48698976/107571048-56d6bc00-6bb8-11eb-9eaf-bfcf7115dab5.png)
![Screen Shot 2021-02-10 at 15 40 35](https://user-images.githubusercontent.com/48698976/107571055-5b02d980-6bb8-11eb-96b4-320b712bae56.png)

**Comment by xotypeco** [comment]
sorry, didn't realize images weren't getting through

here's old vs new forms ![image](https://user-images.githubusercontent.com/52611676/107572804-53d8cd00-6bb2-11eb-91b9-fba26163e3b0.png)

![image](https://user-images.githubusercontent.com/52611676/107572820-589d8100-6bb2-11eb-92bb-0ab31dc8223c.png)

and here's the images I added as reference from other fonts, recursive and myriad 

![image](https://user-images.githubusercontent.com/52611676/107572892-70750500-6bb2-11eb-949c-0eaac1e0032d.png)

![image](https://user-images.githubusercontent.com/52611676/107572906-75d24f80-6bb2-11eb-80ed-29c245474bfa.png)

I don't know how factual this is, but I was told that the reason for strictly vertical static king diacritics is older metal typesetting being unable to tuck them to the right. 

tucked seems to be the preference, since it's closer to how the forms are added when they're being written: circumflex is added first, then the secondary form. (plus it's more compact and less visually jarring.)

will look at legibility again, thanks viviana.

**Comment by vv-monsalve** [comment]
> tucked seems to be the preference, since it's closer to how the forms are added when they're being written: circumflex is added first, then the secondary form. (plus it's more compact and less visually jarring.)

Yes, this is what I meant by 'preferred'. The position itself is not the issue, but to ensure the legibility by checking the above. Those were some of the observations done by Crystaltype on another project ;)

**Comment by vv-monsalve** [comment]
PS. Please wait for me to push the new files. Thanks!

**Comment by xotypeco** [comment]
> PS. Please wait for me to push the new files. Thanks!

will do.

**Comment by xotypeco** [comment]
Vietnamese updates made and pushed.

changed: 

tilde is significantly narrower throughout the weights
grave and acute narrowed a bit at the bottom of the form
grave and acute moved away from circumflexes

not related to the Vietnamese, but I also noticed the files' basic dimensions hadn't gotten updated with the upscale from 1000 UPM to 2000 UPM, so I corrected those in all weights, in the interface (but not in any custom parameters).

so, for example, all the values here are doubled from what they previously were.

![Screen Shot 2021-02-15 at 11 59 23 AM](https://user-images.githubusercontent.com/52611676/107979802-d253b700-6f84-11eb-88a5-d2a5e33a5002.png)

**Comment by vv-monsalve** [comment]
Hi @xotypeco,
New Vietnamese previews after pulling the latest files in the repo at commit 7029d4192528e4c6dabb718eff81565478af7880, produced new fonts and run some test.

I only saw changes in the `Big_Shoulders.glyphs` Are this already included for the Inline and Stencil variants?

**Bigh Shoulders Text**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/108264408-7c724100-7135-11eb-99b4-d86b31934691.gif)

**Big Shoulders Display**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/108277668-c8c67c80-7147-11eb-9f62-b877f8c605aa.gif)

**Comment by xotypeco** [comment]
changes aren't included in Stencil or Inline yet. wanted to make sure it worked before going into those two. ok to do so since these now export & read ok?

**Comment by vv-monsalve** [comment]
Well, my source of doubt was in the lighter weights, particularly at small sizes as the more demanding scenario. So after inspecting the BigShouldersText-Thin in detail, I would suggest the following:

- Dot below should be to the right of "y.". It is the used way as it saves vertical space and in Vietnamese "y." isn't followed by another letter, so spacing is not a problem.
- Breve looks like is touching the A in small sizes.
- In đ, the length of "-" could be increased to the left to increase legibility. Same for Đ but centred or maybe a little bit to the right.
- Hook above loses legibility at small sizes and could be confused with another mark, like grave.
- Grave and tilde look lighter than the other marks. 

**BigShouldersText-Thin 16pt**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/108286171-996b3c00-7156-11eb-8ca3-3557c52c29c3.png)

**BigShouldersText-Thin 21pt**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/108286277-cc153480-7156-11eb-9e35-af0934b339c1.png)

**BigShouldersText-Thin 36pt**

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/108286338-e4854f00-7156-11eb-9e88-32db6148c480.png)

**Comment by xotypeco** [comment]
>Dot below should be to the right of "y.". It is the used way as it saves vertical space and in Vietnamese "y." isn't followed by another letter, so spacing is not a problem.

you mean, like this? verifying because I haven't seen that. if so, cool!

![Screen Shot 2021-02-17 at 8 42 11 PM](https://user-images.githubusercontent.com/52611676/108297357-c15f9d00-7160-11eb-97ad-16e7e8836d79.png)

**Comment by vv-monsalve** [comment]
> you mean, like this? verifying because I haven't seen that. if so, cool!

Yes, like that, cool indeed :)

**Comment by xotypeco** [comment]
done and pushed per suggestions above. the hook is bigger now but not by a ton. I'm honestly not worried about some difficulty in reading at anything below 24pt, because this is a titling face & is being used as such citywide.

**Comment by vv-monsalve** [comment]
I've pulled the latest files at commit 8d075eaccf9edb4a127f218b71a150ace943c9a5 and performed som comparisons with the previous font.
The change on the hook is not noticeable.

![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/109736716-c8d86a80-7b92-11eb-944b-802cc3a1d9c6.gif)
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/109736745-d1c93c00-7b92-11eb-8220-4bd9e0f2e8d6.gif)

**Comment by xotypeco** [comment]
I'm fine with the hook. it's never being used this small; it's for headlines. grave, acute, and bar through D & d are much better.

**Comment by vv-monsalve** [comment]
> I'm fine with the hook. it's never being used this small; it's for headlines. grave, acute, and bar through D & d are much better.

Please bear in mind that being published in Google Fonts, the number of users could grow exponentially and therefore the uses, and they would differ from the uses that the city as it's natural niche make of the font. Also, the previews here correspond to the Text family.

Maybe @crystaltype could give an expert opinion here :)

Other than that, please bring these Vietnamese improvements to the Inline and Display variants and let me know when they are ready to continue with the publishing process.

**Comment by xotypeco** [comment]
all this is pushed in regular, Stencil, and Inline. Inline's tilde has been further narrowed by quite a bit, so you'll more than likely notice that.

**Comment by vv-monsalve** [comment]
@xotypeco These are the latest images for BigShoulders after commit 4eb801fd9a8dc7c264144a8bcddae964986bb99d

**Text Family**

**OS X High Sierra Safari_11**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/117389063-63199f00-aeb1-11eb-9751-3fe262c76023.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/117389079-690f8000-aeb1-11eb-837a-581eabdb919b.gif)
**Windows 10 Edge_18**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/117389083-6a40ad00-aeb1-11eb-96a9-f0e33989413e.gif)

**Comment by vv-monsalve** [comment]
### SemiBold, Bold, ExtraBold, Black

**OS X High Sierra Safari_11**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/117389180-96f4c480-aeb1-11eb-933e-a752018569f5.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/117389196-9d833c00-aeb1-11eb-863b-ce84f27e999e.gif)
**Windows 10 Edge_18**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/117389203-9eb46900-aeb1-11eb-9a48-45d500cfa317.gif)
