### ISSUE TITLE
Instance coordinates are not multiples of 100

### ISSUE THREAD

**Issue by m4rc1e** [xotypeco/big_shoulders#9]
```
    * FAIL: Instance "10pt Light" wght value is "257.0". It should be "300.0" [code: bad-coordinate]
    * FAIL: Instance "10pt Regular" wght value is "385.0". It should be "400.0" [code: bad-coordinate]
    * FAIL: Instance "10pt Medium" wght value is "450.0". It should be "500.0" [code: bad-coordinate]
    * FAIL: Instance "10pt SemiBold" wght value is "514.0". It should be "600.0" [code: bad-coordinate]
    * FAIL: Instance "10pt Bold" wght value is "642.0". It should be "700.0" [code: bad-coordinate]
    * FAIL: Instance "10pt ExtraBold" wght value is "771.0". It should be "800.0" [code: bad-coordinate]
    * FAIL: Instance "72pt Light" wght value is "257.0". It should be "300.0" [code: bad-coordinate]
    * FAIL: Instance "72pt Regular" wght value is "385.0". It should be "400.0" [code: bad-coordinate]
    * FAIL: Instance "72pt Medium" wght value is "450.0". It should be "500.0" [code: bad-coordinate]
    * FAIL: Instance "72pt SemiBold" wght value is "514.0". It should be "600.0" [code: bad-coordinate]
    * FAIL: Instance "72pt Bold" wght value is "642.0". It should be "700.0" [code: bad-coordinate]
    * FAIL: Instance "72pt ExtraBold" wght value is "771.0". It should be "800.0" [code: bad-coordinate]
```

All of these values need to comply with our wip spec, https://github.com/googlefonts/gf-docs/tree/master/Spec#variable-fonts.

If you delete the axis-locations customParameters in the masters, it will fix this.

**Comment by xotypeco** [comment]
but that results in this:

    * FAIL: OS/2 usWeightClass expected value for '10pt Thin' is 250 but this font has 100.
 GlyphsApp users should set a Custom Parameter for 'Axis Location' in each master to ensure that the information is accurately built into variable fonts. [code: bad-value]

    Result: FAIL

**Comment by xotypeco** [comment]
update on this, with some research: MS docs indicate that 100 is an acceptable value for usWeightClass for Thin [here](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass)

so, in light of that, is this FAIL actually an update necessary to fontbakery's check for that value?

**Comment by m4rc1e** [comment]
> removing it lets all the weights pass, but results in this, which is the only remaining FAIL:

This is a false positive. We need to fix this in fontbakery. Please ignore it.

**Comment by xotypeco** [comment]
argh. ok, thanks, new output files coming soon. this is the last FAIL I wasn't understanding.

**Comment by xotypeco** [comment]
all fonts updated, cupcakes in every fontbakery check. only FAILs still existing are complaints about a 4000UPM em in Inline.

**Comment by xotypeco** [comment]
this is finished as far as I can see, awaiting further comment or addition to google fonts.
